server {
    listen 162.55.6.173:80;
    server_name apps.coffee.pm releases.coffee.pm ota.coffee.pm;

    server_tokens off;
    return 403;
}

server {
    listen 162.55.6.173:443 ssl;
    server_name apps.coffee.pm releases.coffee.pm ota.coffee.pm;

    server_tokens off;
    autoindex off;

    ssl_certificate /etc/letsencrypt/live/coffee.pm/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coffee.pm/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Frame-Options "DENY" always;
    add_header Content-Security-Policy "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none';" always;

    return 403;
}
